# Docker Compose Override for Local Development
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

version: '3.8'

services:
  reading-tracker:
    # Override for local development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - CORS_ORIGIN=http://localhost:5173
    # Mount source code for development
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - reading_data:/app/data
      - reading_logs:/app/logs
      # Prevent overwriting node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
    # Enable development command
    command: ["sh", "-c", "cd /app/backend && npm run dev"]
    # Add development ports
    ports:
      - "3000:3000"
      - "5173:5173"